name       : haskell-tls
version    : 1.3.9
release    : 1
source     :
    - http://hackage.haskell.org/package/tls-1.3.9/tls-1.3.9.tar.gz : 81355e16528796d3097719e74f7f1f8cae50daed06926d1995731bab8e02267b
license    : BSD-3-Clause
component  : programming.haskell
summary    : Native Haskell TLS and SSL protocol implementation for server and client. 
description: |
    Native Haskell TLS and SSL protocol implementation for server and client. 
builddeps  :
    - haskell-cabal-install
    - haskell-hans
    - haskell-x509-validation
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
