name       : haskell-tls
version    : 1.5.4
release    : 3
source     :
    - https://hackage.haskell.org/package/tls-1.5.4/tls-1.5.4.tar.gz : ce42bfa581a50f62776581da4b86408ebb1a51bc6cb2f95ad0a2ac7caa19a437
license    : BSD-3-Clause
component  : programming.haskell
summary    : Native Haskell TLS and SSL protocol implementation for server and client.
description:
    Native Haskell TLS and SSL protocol implementation for server and client.
builddeps  :
    - haskell-async-devel
    - haskell-cabal-install
    - haskell-cereal-devel
    - haskell-network-devel
    - haskell-x509-store-devel
    - haskell-x509-validation-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-cereal-devel
        - haskell-network-devel
        - haskell-x509-store-devel
        - haskell-x509-validation-devel
networking : yes
setup      : |
    %cabal_configure -fnetwork
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
