name       : haskell-tls
version    : 1.4.0
release    : 2
source     :
    - https://hackage.haskell.org/package/tls-1.4.0/tls-1.4.0.tar.gz : 83290896640403b167d3ae4ea6075f69565a98a5198049a6d98ec35d6bf417ba
license    : BSD-3-Clause
component  : programming.haskell
summary    : Native Haskell TLS and SSL protocol implementation for server and client.
description: "Native Haskell TLS and SSL protocol implementation for server and client. \n"
builddeps  :
    - haskell-async
    - haskell-cabal-install
    - haskell-hans
    - haskell-network
    - haskell-x509-validation
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
